import Head from 'next/head'
import Layout from "../components/layout";
import Hero from "./heroSection";

export default function Home() {
  return (
    <Layout>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero/>
      </div>      
    </Layout>
  )
}


