import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/about">Yard</a>
        </h1>
        <p className={styles.content}>
          Bringing web hosting to your door step
        </p>
        <div className = 'text-center'>
          <a className='text'>Get started</a>
          <a className={styles.pill}>Sign in</a>          
        </div>

      </main>

      <footer className='text-align'>
      </footer>
    </div>
  )
}


